<?php
/**
 * @file
 * Code for the GSB Feature Voices Display feature.
 */

include_once 'gsb_feature_voices_display.features.inc';

/**
  * Implements hook_form_FORM_ID_alter().
  */
function gsb_feature_voices_display_form_views_content_views_panes_content_type_edit_form_alter(&$form, &$form_state) {

  // Alter 'Voices filters' content pane settings form.
  if ($form_state['pane']->subtype == 'voices_filters-voices_filters_pane' && $form_state['view']->name == 'voices_filters'
    && $form_state['view']->current_display == 'voices_filters_pane') {
      $conf = $form_state['conf'];

      $form['exposed']['filter-field_industry_tid']['expose_to_visitor']['#weight'] = -98;
      $form['exposed']['filter-field_industry_tid']['expose_to_visitor']['#title'] = '<span class="hide_ind">Industry</span>';
      $form['exposed']['filter-field_industry_tid']['field_industry_tid']['#weight'] = -87;
      $form['exposed']['filter-field_industry_tid']['field_industry_tid']['#theme'] = 'select';
      $form['exposed']['filter-field_industry_tid']['#title'] = t('Allow the user to filter by Industry');

      $form['exposed']['filter-field_region_of_interest_tid']['expose_to_visitor']['#title'] = '<span class="hide_region">Region</span>';
      $form['exposed']['filter-field_region_of_interest_tid']['expose_to_visitor']['#weight'] = -97;
      $form['exposed']['filter-field_region_of_interest_tid']['field_region_of_interest_tid']['#theme'] = 'select';
      $form['exposed']['filter-field_region_of_interest_tid']['#title'] = t('Allow the user to filter by Region');
      $form['links']['#access'] = FALSE;
      $form['comments']['#access'] = FALSE;

  //  drupal_add_js(array('gsb_feature_all_research_display' => array("topics" => $topics)), 'setting');
      drupal_add_js(drupal_get_path('module', 'gsb_feature_voices_display') . '/js/gsb_feature_voices_display.js');
    //$form['#validate'][] = 'gsb_feature_all_research_display_pane_form_validate';


/*       $form['exposed']['filter_by_industry'] = array(
        '#title' => t('Allow the user to filter by Industry'),
        '#type' => 'checkbox',
        '#weight' => -2,
        '#default_value' => !empty($conf['filter_by_industry']) ? $conf['filter_by_industry'] : '',
      );

      $form['exposed']['filter_by_region'] = array(
        '#title' => t('Allow the user to filter by Region'),
        '#type' => 'checkbox',
        '#weight' => -1,
        '#default_value' => !empty($conf['filter_by_region']) ? $conf['filter_by_region'] : '',
      ); */

      $form['#validate'][] = 'gsb_feature_voices_display_form_validate';
      $form['#submit'][] = 'gsb_feature_voices_display_form_submit';
  }
}

/**
 * Validate handler for views_content_views_panes_content_type_edit_form.
 */
function gsb_feature_voices_display_form_validate(&$form, &$form_state) {
  
}

/**
 * Submit handler for views_content_views_panes_content_type_edit_form.
 *  - Save filter fields in pane config.
 */
function gsb_feature_voices_display_form_submit($form, &$form_state) {
  $form_state['conf']['filter_by_industry'] = $form_state['values']['filter_by_industry'];
  $form_state['conf']['filter_by_region'] = $form_state['values']['filter_by_region'];
}

/**
  * Implements hook_form_FORM_ID_alter().
  */
function gsb_feature_voices_display_form_views_exposed_form_alter(&$form, &$form_state) {
  
}
