<?php
/**
 * @file
 * Code for the GSB Feature Voices Display feature.
 */

include_once 'gsb_feature_voices_display.features.inc';

/**
  * Implements hook_form_FORM_ID_alter().
  */
function gsb_feature_voices_display_form_views_content_views_panes_content_type_edit_form_alter(&$form, &$form_state) {
   //dpm($form_state['pane']->subtype);
   //dpm($form_state['view']->name);
   //dpm($form_state['view']->current_display);
  // Alter 'Voices filters' content pane settings form.
  if ($form_state['pane']->subtype == 'voices_filters-voices_filters_pane' && $form_state['view']->name == 'voices_filters'
    && $form_state['view']->current_display == 'voices_filters_pane') {
      $conf = $form_state['conf'];

      $form['exposed']['filter-field_industry_tid']['expose_to_visitor']['#weight'] = -98;
      $form['exposed']['filter-field_industry_tid']['expose_to_visitor']['#title'] = '<span class="hide_ind">Industry</span>';
      $form['exposed']['filter-field_industry_tid']['field_industry_tid']['#weight'] = -87;
      $form['exposed']['filter-field_industry_tid']['field_industry_tid']['#theme'] = 'select';
      $form['exposed']['filter-field_industry_tid']['#title'] = t('Allow the user to filter by Industry');

      $form['exposed']['filter-field_region_of_interest_tid']['expose_to_visitor']['#title'] = '<span class="hide_region">Region</span>';
      $form['exposed']['filter-field_region_of_interest_tid']['expose_to_visitor']['#weight'] = -97;
      $form['exposed']['filter-field_region_of_interest_tid']['field_region_of_interest_tid']['#theme'] = 'select';
      $form['exposed']['filter-field_region_of_interest_tid']['#title'] = t('Allow the user to filter by Region');
      $form['links']['#access'] = FALSE;
      $form['comments']['#access'] = FALSE;

  //  drupal_add_js(array('gsb_feature_all_research_display' => array("topics" => $topics)), 'setting');
      drupal_add_js(drupal_get_path('module', 'gsb_feature_voices_display') . '/js/gsb_feature_voices_display.js');
    //$form['#validate'][] = 'gsb_feature_all_research_display_pane_form_validate';


/*       $form['exposed']['filter_by_industry'] = array(
        '#title' => t('Allow the user to filter by Industry'),
        '#type' => 'checkbox',
        '#weight' => -2,
        '#default_value' => !empty($conf['filter_by_industry']) ? $conf['filter_by_industry'] : '',
      );

      $form['exposed']['filter_by_region'] = array(
        '#title' => t('Allow the user to filter by Region'),
        '#type' => 'checkbox',
        '#weight' => -1,
        '#default_value' => !empty($conf['filter_by_region']) ? $conf['filter_by_region'] : '',
      ); */

      $form['#validate'][] = 'gsb_feature_voices_display_form_validate';
      $form['#submit'][] = 'gsb_feature_voices_display_form_submit';
  }
  if ($form_state['view']->name == 'voices_filters'
    && $form_state['pane']->subtype == 'voices_filters-panel_pane_1'  && $form_state['view']->current_display == 'panel_pane_1') {
     $conf = $form_state['conf'];
     $form['exposed']['filter-field_academic_area_single_tid']['#title'] = '<span class="hide-area-one">Academic Area</span>';
     $form['exposed']['filter-field_field_of_study_tid']['#title'] = '<span class="hide-area-two">Field of Study</span>';

     $form['CTA'] = array(
        '#type' => 'fieldset',
        '#title' => t('CTA'),
      );
      $form['CTA']['cta_title'] = array(
        '#title' => t('Text'),
        '#type' => 'textfield',
        '#description' => 'Enter an action statement.',
        '#weight' => 1,
        '#default_value' => !empty($conf['cta_title']) ? $conf['cta_title'] : '',
      );
      $form['CTA']['cta_url'] = array(
        '#title' => t('URL'),
        '#type' => 'textfield',
        '#weight' => 2,
        '#default_value' => !empty($conf['cta_url']) ? $conf['cta_url'] : '',
      );
    $form['#validate'][] = 'gsb_feature_voices_display_form_validate';
    $form['#submit'][] = 'gsb_feature_voices_display_form_submit';
    drupal_add_js(drupal_get_path('module', 'gsb_feature_voices_display') . '/js/gsb_feature_voices_list_cta.js');  
   
  }
}

/**
 * Validate handler for views_content_views_panes_content_type_edit_form.
 */
function gsb_feature_voices_display_form_validate(&$form, &$form_state) {
  if ($form_state['values']['cta_title'] != '' && $form_state['values']['cta_url'] == '') {
    form_set_error('cta_url', t('CTA Url is required.'));
  }
  if ($form_state['values']['cta_title'] == '' && $form_state['values']['cta_url'] != '') {
    form_set_error('cta_title', t('CTA title is required.'));
  }
}

/**
 * Submit handler for views_content_views_panes_content_type_edit_form.
 *  - Save filter fields in pane config.
 */
function gsb_feature_voices_display_form_submit($form, &$form_state) {
  $form_state['conf']['filter_by_industry'] = $form_state['values']['filter_by_industry'];
  $form_state['conf']['filter_by_region'] = $form_state['values']['filter_by_region'];
  $form_state['conf']['cta_url'] = $form_state['values']['cta_url'];
  $form_state['conf']['cta_title'] = $form_state['values']['cta_title'];
}

/**
  * Implements hook_form_FORM_ID_alter().
  */
function gsb_feature_voices_display_form_views_exposed_form_alter(&$form, &$form_state) {
  
}

/**
 * Implements hook_panels_pane_content_alter().
 *  - Alter News by Criteria content pane title to be linked to a custom URL.
 */
function gsb_feature_voices_display_panels_pane_content_alter($content, $pane, $args, $context) {
  if ($content && $content->subtype == 'voices_filters-panel_pane_1') {
    if (!empty($pane->configuration['cta_title'])) {
      $url_parts = drupal_parse_url($pane->configuration['cta_url']);
      $url_parts['html'] = TRUE;
      $content->content['#markup'] .= '<div class="voices_display_list_cta">' . l($pane->configuration['cta_title'], $url_parts['path'], $url_parts) . '</div>';
    }
  }
}
